model_list:
  - model_name: chat-groq
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_API_KEY
  - model_name: embed-voyage
    litellm_params:
      model: voyage/voyage-3.5-lite
      api_key: os.environ/VOYAGE_API_KEY
